apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-image-updater-demo
  namespace: argocd
  annotations:
    argocd-image-updater.argoproj.io/image-list: greghaines/demo-app:0.0.x
    argocd-image-updater.argoproj.io/write-back-method: git:secret:argocd/git-creds
    argocd-image-updater.argoproj.io/mywebapp.update-strategy: semver
spec:
  project: default

  source:
    repoURL: https://github.com/hainesgreg/argo-demo
    targetRevision: HEAD
    path: .
    kustomize: {}
  
  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
