apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argo-image-updater-demo
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/hainesgreg/argo-demo
    targetRevision: HEAD
    path: .

  destination:
    server: https://kubernetes.default.svc
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
